apiVersion: v1
kind: Service
metadata:
  labels:
    app: sre-assignment
  name: sre-assignment
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32168
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sre-assignment
  sessionAffinity: None
  type: NodePort